calorie_tracker_app/urls.py
from calorie_tracker_app.apps import CalorieTrackerAppConfig
from django.urls import path
from . import views

app_name = "calorie_tracker_app"

urlpatterns = [
    path('', views.calorie_tracker, name="index"),
    path('delete/<int:id>', views.delete_consume, name="delete_consume"),
]

forum/urls.py
from django.urls import path
from . import views
# app_name = 'forum'
urlpatterns = [
    path("", views.forum, name="forum"),
    path("add_post", views.add_post, name="forum_add_post"),
    path("post/<str:slug>", views.post_detail, name="forum_post_detail"),
    path("add_comment", views.add_comment, name="forum_add_comment"),
    path("delete_post", views.delete_post, name="forum_delete_post"),
    path("delete_comment", views.delete_comment, name="forum_delete_comment"),
    # path("discussion/<str:slug>/reply", views.replies, name="replies"),
    # path("discussion/<str:slug>/comment", views.comment, name="comment"),
    # path("discussion/<str:slug>/update", views.discussionUpdate, name="discussionUpdate"),
    # path("discussion/<str:slug>/delete", views.discussionDelete, name="discussionDelete"),
    #path("discussion/<int:pk>/", views.replyUpdate, name="replyUpdate"),

    path("base/", views.base_temp, name="base"),

]

prohealth/urls.py
from django.contrib import admin
from django.urls import path,include
from webapp.views import home

# app_name = CalorieTrackerAppConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapp/', include('webapp.urls')),
    path('workout-buddy/', include('workout_buddy.urls')),
    path('workout-tracker/', include('workout_tracker.urls')),
    path('calorie-tracker/', include('calorie_tracker_app.urls')), 
    path('forum/', include('forum.urls')),
    # path(r'^$', views.login), # index / login page
    # path(r'^user/register$', views.register), # get register page / register user
    # path(r'^user/login$', views.login), # logs in existing user
    # path(r'^user/logout$', views.logout), # destroys user session
    # path(r'^dashboard$', views.dashboard), # get dashboard
    # path(r'^workout$', views.new_workout), # get workout page / add workout
    # path(r'^workout/(?P<id>\d*)$', views.workout), # get workout / update workout
    # path(r'^workout/(?P<id>\d*)/exercise$', views.exercise), # add exercise
    # path(r'^workout/(?P<id>\d*)/complete$', views.complete_workout), # complete workout
    # path(r'^workout/(?P<id>\d*)/edit$', views.edit_workout), # edit workout
    # path(r'^workout/(?P<id>\d*)/delete$', views.delete_workout), # delete workout
    # path(r'^workouts$', views.all_workouts), # get all workouts
    # path(r'^legal/tos$', views.tos), # get terms of service
    # # path("", views.forum, name="forum"),
    # path("add_post", views.add_post, name="forum_add_post"),
    # path("post/<str:slug>", views.post_detail, name="forum_post_detail"),
    # path("add_comment", views.add_comment, name="forum_add_comment"),
    # path("delete_post", views.delete_post, name="forum_delete_post"),
    # path("delete_comment", views.delete_comment, name="forum_delete_comment"),
    # path("counselor-forum", views.counselor_forum, name="counselor_forum"),
    path('', home, name='home'),
    # path('delete/<int:id>', delete_consume, name="delete_consume"),
    # path('', views.index, name='index'),
    # path('about/', views.about, name='about'),
    # path('workout/', views.workout, name='workout'),
    # path('friends/', views.friends, name='friends'),
    # path('profile/', views.profile, name='profile'),
    # path('profile_edit/', views.profile_edit, name='profile_edit'),
]



   

calorie_tracker_app/models.py
from django.db.models import Model, ForeignKey, CASCADE
from django.db.models.fields import (CharField, FloatField, IntegerField)
from django.contrib.auth import get_user_model
User = get_user_model()

 #Create your models here.
class FoodModel(Model):
    
    name = CharField(("Food"),max_length=255)
    calories = IntegerField(("Calories"),max_length=255)
    carbs = FloatField(("Carbohydrate"),max_length=255)
    fats = FloatField(("Fat"),max_length=255)
    protein = FloatField(("Protein"),max_length=255)
    

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Food'
        verbose_name_plural = 'Foods'
        
class ConsumeModel(Model):
    user = ForeignKey(User, on_delete=CASCADE)
    food_consumed = ForeignKey(FoodModel, on_delete=CASCADE)

    def __str__(self):
        return f'{self.user.username} {self.food_consumed.name}'

    class Meta:
        verbose_name = 'Consume'
        verbose_name_plural = 'Consumes'

calorie_tracker_app/views.py
import datetime
from calorie_tracker_app.models import ConsumeModel, FoodModel
from django.shortcuts import redirect, render
import pandas as pd
import csv

# Create your views here.
def calorie_tracker(request):

    if request.method == "POST":
        food_consumed = request.POST['food_consumed']
        consume = FoodModel.objects.get(name=food_consumed)
        user = request.user
        consume = ConsumeModel(user=user, food_consumed=consume)
        consume.save()
        foods = FoodModel.objects.order_by().all()
        
        data = []
        field_names = ['date', 'time', 'calories']
        calories = 0
        date = datetime.datetime.now().date()
        time = datetime.datetime.now().time()

        consumed_food = ConsumeModel.objects.order_by().filter(user=request.user)

        for food in consumed_food:
            calories += food.food_consumed.calories

        progress = {'date': date, 'time': time, 'calories': calories}
        data.append(progress)

        with open('calorie_tracker_app/calories.csv', 'a', newline='') as f_object:
            dictwriter_object = csv.DictWriter(f_object, fieldnames=field_names)
            dictwriter_object.writerow(progress)

    else:
        foods = FoodModel.objects.order_by().all()
        
    consumed_food = ConsumeModel.objects.order_by().filter(user=request.user)

    # print(calories)
    return render(request, 'calorie_tracker_app/index.html', {'foods': foods, 'consumed_food': consumed_food})

def delete_consume(request, id):
    consumed_food = ConsumeModel.objects.get(id=id)
    if request.method == 'POST':
        consumed_food.delete()
        data = []
        field_names = ['date', 'time', 'calories']
        calories = 0
        date = datetime.datetime.now().date()
        time = datetime.datetime.now().time()

        consumed_food = ConsumeModel.objects.order_by().filter(user=request.user)

        for food in consumed_food:
            calories += food.food_consumed.calories

        progress = {'date': date, 'time': time, 'calories': calories}
        data.append(progress)

        with open('calorie_tracker_app/calories.csv', 'a') as f_object:
            dictwriter_object = csv.DictWriter(f_object, fieldnames=field_names)
            dictwriter_object.writerow(progress)
            f_object.close()
        return redirect('/calorie-tracker/')
    return render(request, 'calorie_tracker_app/delete.html')

calorie_tracker_app/templates/calorie_tracker_app/delete.html
{% extends "webapp/base-temp.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'workout_buddy/landing.css' %}">
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
{% endblock style %}

{% block body %}
{% block submenu %}
<!-- Sidebar -->
<nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse" style="background-color: #0a0a0a;margin-top: 13vh;">
    <div class="position-sticky sidebar-sticky" style="background-color: #0a0a0a; margin-top: 0.5rem;">
        <div class="list-group list-group-flush" style="background-color: #0a0a0a;">
            <!-- <a href="{% url 'home' %}" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
          <i class="fa-solid fa-house"></i><span> Home</span>
        </a>
        <hr> -->
            <a href="{% url 'dashboard' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                    class="fa-solid fa-dumbbell"></i><span> Workout Recommendations</span>
            </a>
            <hr>
            <a href="{% url 'diet' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                    class="fa-solid fa-pot-food fa-lg"></i><span>Diet Recommendations</span>
            </a>
            <hr>
            <a href="{% url 'workout_buddy' %}" class="list-group-item list-group-item-action py-2 ripple"
                aria-current="true">
                <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Workout Buddy</span>
            </a>

            <span> <a href="{% url 'friends' %}" class="list-group-item list-group-item-action py-2 ripple"
                    aria-current="true">
                    <i class="fa-solid fa-user-group fa-fw me-3" style="margin-left: 1.5rem;"></i><span>Friends</span>
                </a></span>
            <span>
                <hr>

                <a href="{% url 'progress' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fa-duotone fa-chart-simple fa-lg"></i><span> Progress</span>
                </a>
                <hr>

                <a href="{% url 'workout-tracker' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fas fa-tachometer-alt fa-fw me-3"></i><span>Workout Tracker</span>
                </a>
                <span> <a href="{% url 'new-workout' %}" class="list-group-item list-group-item-action py-2 ripple">
                        <i class="fa-solid fa-plus" style="margin-left: 1.5rem;"></i><span> Add Workout</span>
                    </a> </span>
                <span> <a href="{% url 'all-workout' %}" class="list-group-item list-group-item-action py-2 ripple">
                        <i class="fa-solid fa-list" style="margin-left: 1.5rem;"></i><span> View All Workouts</span>
                    </a> </span>
                <hr>
                <a href="{% url 'calorie_tracker_app:index' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fa-solid fa-tally"></i><span>Calorie Tracker</span>
                </a>
                <hr>
                <a href="{% url 'forum' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fa-solid fa-users"></i><span>ProHealth Community</span>
                </a>
                <hr>
                <a href="{% url 'profile' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fa-solid fa-user fa-fw me-3"></i><span>Profile</span>
                </a>


        </div>
    </div>
</nav>
<!-- Sidebar -->
{% endblock submenu %}
<main style="margin-top: 58px;">
    <div class="container pt-4">
        <div class="row m-5">
            <div class="col-md-12">
                <form method="POST">

                    {% csrf_token %}
                    <h2 style="text-align:center">Are you sure you want to delete this item? <br> <button type="submit"
                            class="btn btn-danger">Delete</button></h2>

                </form>
            </div>
        </div>
    </div>

</main>
{% endblock body %}

calorie_tracker_app/templates/calorie_tracker_app/index.html
{% extends "webapp/base-temp.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'workout_buddy/landing.css' %}">
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
{% endblock style %}

{% block body %}
{% block submenu %}
<!-- Sidebar -->
<nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse" style="background-color: #0a0a0a;margin-top: 13vh;">
    <div class="position-sticky sidebar-sticky" style="background-color: #0a0a0a; margin-top: 0.5rem;">
        <div class="list-group list-group-flush" style="background-color: #0a0a0a;">
            <!-- <a href="{% url 'home' %}" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
          <i class="fa-solid fa-house"></i><span> Home</span>
        </a>
        <hr> -->
            <a href="{% url 'dashboard' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                    class="fa-solid fa-dumbbell"></i><span> Workout Recommendations</span>
            </a>
            <hr>
            <a href="{% url 'diet' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                    class="fa-solid fa-pot-food fa-lg"></i><span>Diet Recommendations</span>
            </a>
            <hr>
            <a href="{% url 'workout_buddy' %}" class="list-group-item list-group-item-action py-2 ripple"
                aria-current="true">
                <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Workout Buddy</span>
            </a>

            <span> <a href="{% url 'friends' %}" class="list-group-item list-group-item-action py-2 ripple"
                    aria-current="true">
                    <i class="fa-solid fa-user-group fa-fw me-3" style="margin-left: 1.5rem;"></i><span>Friends</span>
                </a></span>
            <span>
                <hr>

                <a href="{% url 'progress' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fa-duotone fa-chart-simple fa-lg"></i><span> Progress</span>
                </a>
                <hr>

                <a href="{% url 'workout-tracker' %}" class="list-group-item list-group-item-action py-2 ripple"><i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Workout Tracker</span>
                </a>
                <span> <a href="{% url 'new-workout' %}" class="list-group-item list-group-item-action py-2 ripple">
                        <i class="fa-solid fa-plus" style="margin-left: 1.5rem;"></i><span> Add Workout</span>
                    </a> </span>
                <span> <a href="{% url 'all-workout' %}" class="list-group-item list-group-item-action py-2 ripple">
                        <i class="fa-solid fa-list" style="margin-left: 1.5rem;"></i><span> View All Workouts</span>
                    </a> </span>
                <hr>
                <a href="{% url 'calorie_tracker_app:index' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fa-solid fa-tally"></i><span>Calorie Tracker</span>
                </a>
                <hr>
                <a href="{% url 'forum' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fa-solid fa-users"></i><span>ProHealth Community</span>
                </a>
                <hr>
                <a href="{% url 'profile' %}" class="list-group-item list-group-item-action py-2 ripple"><i
                        class="fa-solid fa-user fa-fw me-3"></i><span>Profile</span>
                </a>


        </div>
    </div>
</nav>
<!-- Sidebar -->
{% endblock submenu %}
<main style="margin-top: 58px;">
    <div class="container pt-4">
        <br><br>
        <div style="text-align:center" class="row">

            <form method="POST">
                <div class="row">
                    <div class="form-group row">
                        {% csrf_token %}
                        <label class="col-3 text-white">
                            <strong>Select Food To Add </strong>
                        </label>
                        <select class="col form-control" name="food_consumed" id="food_consumed">
                            {% for food in foods %}
                            <option value="{{food.name}}">{{food}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="row" style="margin-top: 2rem;">
                    <div class="col align-self-center">
                        <button class="banner_btn" type="submit">Add</button>
                    </div>
                </div>
            </form>

        </div>

        <br>

        
        <div class="row">
            <h3 style="text-align:center; color: #fbfbfb;margin: 1rem 0rem 1rem 0rem;">Calorie Goal</h3>
            <div class="col-md" style="margin: 1rem 2rem 1rem 2rem;">
                <div class="progress align-self-center">
                    <div class="progress-bar bg-success" role="progressbar" style="width: 20%" aria-valuenow="0"
                        aria-valuemin="0" aria-valuemax="0"></div>

                </div>
            </div>
        </div>

        <br><br>
        <div class="row">
            <div class="col-md-7">
                <div>
                    <h4 style="text-align:center;color: #fbfbfb;"> Today's Consumption</h4>
                </div>

                <table id="table" class="table table-striped table-light table-bordered">
                    <tr class="bg-info text-black">
                        <th style="text-align:center">Food item</th>
                        <th style="text-align:center">Carbs(gm)</th>
                        <th style="text-align:center">Protein(gm)</th>
                        <th style="text-align:center">Fats(gm)</th>
                        <th style="text-align:center">Calories(Kcal)</th>
                        <th style="text-align:center">Remove Item</th>
                    </tr>
                    {% for c in consumed_food %}
                    <tr>
                        <td style="text-align:center">{{c.food_consumed.name}}</td>
                        <td style="text-align:center">{{c.food_consumed.carbs}}</td>
                        <td style="text-align:center">{{c.food_consumed.protein}}</td>
                        <td style="text-align:center">{{c.food_consumed.fats}}</td>
                        <td style="text-align:center">{{c.food_consumed.calories}}</td>
                        <td style="text-align:center"><a class="btn btn-danger"
                                href="{% url 'calorie_tracker_app:delete_consume' c.pk %}">X</a>
                        </td>
                    </tr>

                    {% endfor %}

                    <tr class="bg-info text-black">
                        <td style="text-align:center" id="name"><b>Total</b></td>
                        <td style="text-align:center" id="totalCarbs"><b></b></td>
                        <td style="text-align:center" id="totalProtien"><b></b></td>
                        <td style="text-align:center" id="totalFats"><b></b></td>
                        <td style="text-align:center" id="totalCalories"><b></b></td>


                    </tr>

                </table>
            </div>

            <div class="col-md-5 ">
                <div class="">
                    <h4 style="text-align:center;color: #fbfbfb;">Today's breakdown</h4>
                </div>
                <div class="card-header text-black" style="background-color: #ff7009; ">
                    <h4 style="text-align:center">Nutrients breakdown</h4>
                </div>
                <div class="col">

                    <canvas id="myChart" width="400" height="400" ></canvas>

                </div>
            </div>
        </div>

    </div>
</main>
{% endblock body %}
{% block script %}
<script>
    var table = document.getElementById("table");
    var carbs = 0, protein = 0, fats = 0, calories = 0;

    for (var i = 1; i < table.rows.length - 1; i++) {
        console.log(table.rows[i].cells[1].innerHTML);
        carbs += parseFloat(table.rows[i].cells[1].innerHTML);
        carbs = Math.round(carbs);
        protein += parseFloat(table.rows[i].cells[2].innerHTML);
        protein = Math.round(protein)
        fats += parseFloat(table.rows[i].cells[3].innerHTML);
        fats = Math.round(fats);
        calories += parseFloat(table.rows[i].cells[4].innerHTML);
        calories = Math.round(calories);
    }
    console.log(fats);

    document.getElementById("totalCarbs").innerHTML = '<b>' + carbs + '(gm)</b>';
    document.getElementById("totalProtien").innerHTML = '<b>' + protein + '(gm)</b>';
    document.getElementById("totalFats").innerHTML = '<b>' + fats + '(gm)</b>';
    document.getElementById("totalCalories").innerHTML = '<b>' + calories + '(Kcal)</b>';

    var calPer = (calories / 2000) * 100;
    document.getElementsByClassName("progress-bar")[0].setAttribute("style", "width:" + calPer + "%");


    var total = carbs + protein + fats;
    var carbsP = Math.round((carbs / total) * 100);
    var protienP = Math.round((protein / total) * 100);
    var fatsP = Math.round((fats / total) * 100);

    var ctx = document.getElementById('myChart').getContext('2d');

    var myChart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: ['Carbs ' + carbsP + '%', 'Protein ' + protienP + '%', 'Fats ' + fatsP + '%'],
            datasets: [{
                label: '# of Votes',
                data: [carbsP, protienP, fatsP],
                backgroundColor: [
                    'rgba(255, 99, 132, 1)', 
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',

                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',

                ],
                borderWidth: 1,
                
            }]
        },
        options: { 
            legend: {
                labels: {
                    fontColor: "#fbfbfb",
                    fontSize: 14
                }
            }
        }

    });

</script>
{% endblock script %}